name: Deploy Spring Boot App

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Build Docker Image
        run: |
          docker build -t myapp:latest .

      - name: Stop Old Container
        run: |
          docker stop myapp || true
          docker rm myapp || true

      - name: Run New Container
        run: |
          docker run -d \
            --name myapp \
            -p 8080:8080 \
            --restart always \
            myapp:latest