name: Deploy Spring Boot App

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Build Docker Image
        run: |
          docker build -t myapp:latest .

      - name: Save Docker Image
        run: |
          docker save myapp:latest -o /tmp/myapp.tar

      - name: File Permission
        run: |
          chmod 644 /tmp/myapp.tar

      - name: Copy Image to VM
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USER }}
          key: ${{ secrets.VM_SSH_KEY }}
          source: "/tmp/myapp.tar"
          target: "/home/${{ secrets.VM_USER }}/"

      - name: Deploy on VM
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USER }}
          key: ${{ secrets.VM_SSH_KEY }}
          script: |
            docker load -i /home/${{ secrets.VM_USER }}/myapp.tar

            docker stop myapp || true
            docker rm myapp || true

            docker run -d \
              --name myapp \
              -p 8080:8080 \
              --restart always \
              myapp:latest

            rm -f /home/${{ secrets.VM_USER }}/myapp.tar